## Part 1: Conceptual Check (15 min)

Test your understanding before diving into the code.

**Question 1:** What is the key difference between a Pandas `Series` and a `DataFrame`?

Series is 1d. DataFrame is 2d

**Question 2:** You run `df.loc[0:3]`. How many rows do you get? What about `df.iloc[0:3]`?

assuming a df with rows labelled 0,1,2,3.... we get 4 rows, because loc is by labels, so we get the labels 0-3. iloc gives us positional index, and only 0,1,2

**Question 3:** You have a DataFrame with a `price` column stored as `object` type (strings like "£45.99"). What problem does this cause, and how do you fix it?

You wont be able to do any mathematical operations, filtering, sorting on this. We need to remove any stray text e.g. £ and cast astype to float

**Question 4:** When would you use `.apply()` instead of a direct vectorised operation like `df['col'] * 2`?

When I'm using my own function where multiple calculations are needed instead of just simple multiplication

**Question 5:** How do you select all numeric columns from a DataFrame, excluding float types?

df.select_dtypes(include="number", exclude="float")
[Honestly i couldnt figure this out from the class material, i had to ask Gemini for help!]

## Part 2: Practical Challenge (30–45 min)

### Scenario: "The Bookshop Analyst"

You're a data analyst for an online bookshop. The operations team has exported their inventory to a CSV and they need your help making sense of it.

---

### Challenge 1: Build and Inspect the Dataset

Create the following DataFrame and perform a health check:

```python
import pandas as pd

books = pd.DataFrame({
    'title': ['The Pragmatic Programmer', 'Clean Code', 'Python Crash Course',
              'Data Science from Scratch', 'Designing Data-Intensive Apps'],
    'author': ['Hunt & Thomas', 'Robert Martin', 'Eric Matthes',
               'Joel Grus', 'Martin Kleppmann'],
    'genre': ['Tech', 'Tech', 'Tech', 'Data', 'Data'],
    'price': [45.99, 38.50, 29.99, 42.00, 55.00],
    'units_sold': [120, 95, 200, 80, 60],
    'in_stock': [True, True, False, True, False]
})
```

**Tasks:**
1. Use `.info()` — how many non-null values does each column have?
2. Use `.describe()` — what's the average price and maximum units sold?
3. Add a `revenue` column: `price × units_sold`.
4. What is the total revenue across all books?

In [64]:
import pandas as pd

books = pd.DataFrame({
    'title': ['The Pragmatic Programmer', 'Clean Code', 'Python Crash Course',
              'Data Science from Scratch', 'Designing Data-Intensive Apps'],
    'author': ['Hunt & Thomas', 'Robert Martin', 'Eric Matthes',
               'Joel Grus', 'Martin Kleppmann'],
    'genre': ['Tech', 'Tech', 'Tech', 'Data', 'Data'],
    'price': [45.99, 38.50, 29.99, 42.00, 55.00],
    'units_sold': [120, 95, 200, 80, 60],
    'in_stock': [True, True, False, True, False]
})

#1
books.info()
#Each has 5 non null values

#2
books.describe()
#Avg price is 42.296 and max units is 200

#3
books["revenue"] = books["price"]*books["units_sold"]
display(books)

#4
print("Total Revenue is: ")
display(books["revenue"].sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5 non-null      object
 1   author      5 non-null      object
 2   genre       5 non-null      object
 3   price       5 non-null      float64
 4   units_sold  5 non-null      int64
 5   in_stock    5 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 333.0+ bytes

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0

Total Revenue is:

21834.3

### Challenge 2: Indexing & Filtering

**Tasks:**
1. Use `.loc` to select only `title` and `revenue` for Data genre books.
2. Use `.iloc` to retrieve the last 3 rows and first 3 columns.
3. Filter books that are **in stock** AND have a **price above £40**.
4. Find the book with the **highest revenue** using `.loc` with `.idxmax()`.

In [44]:
#1
display(books.loc[:,["title","revenue"]])
#2
display(books.iloc[-3:,:3])
#3
display(books[(books["in_stock"]==True) & (books["price"]>=40) ])
#4
display(books.loc[books["revenue"].idxmax(),:])

                           title  revenue
0       The Pragmatic Programmer   5518.8
1                     Clean Code   3657.5
2            Python Crash Course   5998.0
3      Data Science from Scratch   3360.0
4  Designing Data-Intensive Apps   3300.0

                           title            author genre
2            Python Crash Course      Eric Matthes  Tech
3      Data Science from Scratch         Joel Grus  Data
4  Designing Data-Intensive Apps  Martin Kleppmann  Data

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0

title         Python Crash Course
author               Eric Matthes
genre                        Tech
price                       29.99
units_sold                    200
in_stock                    False
revenue                    5998.0
Name: 2, dtype: object

### Challenge 3: Transform, Sort & Rank

**Tasks:**
1. Use `.apply()` to add a `price_tier` column: `'Budget'` (< £35), `'Standard'` (£35–£50), `'Premium'` (> £50).
2. Sort the DataFrame by `revenue` descending.
3. Add a `sales_rank` column using `.rank(ascending=False)`.
4. Use `.map()` to encode `genre` as a number: `{'Tech': 0, 'Data': 1}`.

In [65]:
#1
def pricetier(val):
    if val > 50: 
        return 'Premium'
    elif val >= 35 <=50:
        return 'Standard'
    else:
        return 'Budget'
    
books["price_tier"] = books["price"].apply(pricetier)

display(books)

#2
books.sort_values(by="revenue", ascending=False)
display(books)
#3
books["sales_rank"] = books["units_sold"].rank(ascending=False)
display(books.sort_values(by="sales_rank", ascending=True))
#4
books["genre_code"]= books["genre"].map({'Tech': 0, 'Data': 1})
display(books)

,title,author,genre,price,units_sold,in_stock,revenue,price_tier
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium

,title,author,genre,price,units_sold,in_stock,revenue,price_tier
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget,1.0
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard,2.0
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard,3.0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard,4.0
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium,5.0

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank,genre_code
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard,2.0,0
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard,3.0,0
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget,1.0,0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard,4.0,1
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium,5.0,1

### 🏆 Stretch Challenge (Optional)

The manager wants a report comparing average price and total revenue by `price_tier`. Use `groupby()` to generate this summary. Which tier contributes the most total revenue despite having the lowest average price?

(AI Answer below, no idea how to use .groupby without ai :( )

In [86]:
summary = (
    books.groupby("price_tier")
    .agg(
        avg_price=("price", "mean"),
        total_revenue=("revenue", "sum"),
    )
    .reset_index()
)

display(summary)

  price_tier  avg_price  total_revenue
0     Budget  29.990000         5998.0
1    Premium  55.000000         3300.0
2   Standard  42.163333        12536.3

> *Think of a dataset you might work with in your field. Which Pandas operation from today (indexing, `.apply()`, sorting, or ranking) would be most immediately useful? Why?*

I have a simple dataset which is the digitalisation adoption scores of all departments (it's a metric internally developed). I bucket them into High/Medium/Low adoption, and defining a function + using .apply would help me to immediately sort them into their buckets.